#!/bin/bash

set -e -u

if [[ "$(whoami)" != apy ]]; then
    echo "ERROR: Run this script as user 'apy', e.g. with 'sudo -u apy /home/apy/build-apy-server'"
    exit 1
fi

set -x
cd ~/apertium-apy
# making langNames.db -- hopefully gtweb's disk won't die this time
make
set +x

echo
echo
echo 'apertium-apy is up-to-date! Do "sudo systemctl restart apy" to restart it immediately'
echo
echo 'You may want to also run ./build-html-pages (after apy is restarted)'
echo
