#!/bin/bash

set -e -u

if [[ "$(whoami)" != apy ]]; then
    echo "ERROR: Run this script as user 'apy', e.g. with 'sudo -u apy /home/apy/build-html-pages'"
    exit 1
fi

if ! status=$(systemctl status -n0 apy); then
    echo "ERROR: It seems APY isn't running:"
    echo "${status}"
    echo
    echo "We need APY for compiling apertium-html-tools."
    echo "Please ask someone with sudo to do 'systemctl start apy'."
    exit 1
fi

if ! curl localhost:2737; then
    echo
    echo "WARNING: APY isn't answering; waiting a bit in case it was just started ..."
    echo
    sleep 10
fi

tmp=$(mktemp -t gtweb-html-pages.XXXXXXXX)
trap 'rm -f "${tmp}"' EXIT

set -x
cd ~/apertium-html-tools
for goal in jorgal tolkimine mt mt-testing; do
    export CONFIG=../html-tools-confs/"${goal}".conf
    git checkout -- .
    make clean
    # html-tools config doesn't yet let you restrict locales, TODO
    cat ../html-tools-confs/locales-"${goal}".json > assets/strings/locales.json
    if [[ "${goal}" = mt ]]; then
        # Add a little message in /mt:
        jq '.Translate_Input_Placeholder |= .+"\n\nPrográmmat davvisámegillii jorgalit dušše sánis sátnái." ' < assets/strings/sme.json > "${tmp}"
        /usr/bin/mv "${tmp}" assets/strings/sme.json
        jq '.Translate_Input_Placeholder |= .+"\n\nProgrammene TIL nordsamisk oversetter bare ord for ord." ' < assets/strings/nob.json > "${tmp}"
        /usr/bin/mv "${tmp}" assets/strings/nob.json
        jq '.Translate_Input_Placeholder |= .+"\n\nWhen translating TO North Sámi, we only translate word for word." ' < assets/strings/eng.json > "${tmp}"
        /usr/bin/mv "${tmp}" assets/strings/eng.json
    fi
    make -s -j yeti || make yeti
    rsync -a --delete-after build/ "${goal}"/
done

git checkout -- .
set +x

echo
echo 'Up-to-date! Now try http://gtweb.uit.no/jorgal and translate something'
