#!/bin/bash

set -e -u

if [[ "$(whoami)" != root ]]; then
    echo "Run this script with sudo" >&2
    exit 1
fi

D="$(dirname "$0")"
declare -r D

cd "$D"

set -x

find etc/           -type f -exec install -Dm644 {} /{} \;
find usr/           -type f -exec install -Dm644 {} /{} \;
find usr/local/bin/ -type f -exec install -Dm755 {} /{} \;

systemctl daemon-reload
systemctl enable apy.service restart-apy.timer certbot.timer svn-up-apy.timer
systemctl start  apy.service restart-apy.timer certbot.timer svn-up-apy.timer
# CentOS uses yum-cron.timer run by cron, instead of dnf-automatic.timer

restorecon /etc/firewalld/services/apy.xml
firewall-cmd --permanent --add-service=apy
firewall-cmd --permanent --add-service=https
firewall-cmd --reload

certbot --expand --agree-tos -m unhammer+apertium@mm.st --nginx -n certonly -d gtweb.uit.no
certbot --expand --agree-tos -m unhammer+apertium@mm.st --nginx -n certonly -d jorgal.uit.no
