#!/bin/bash

set -e -u

if [[ "$(whoami)" != root ]]; then
    echo "Run this script with sudo" >&2
    exit 1
fi

D="$(dirname "$0")"
declare -r D

cd "$D"

set -x

find etc/ -type f -exec install -Dm644 {} /{} \;

restorecon /etc/firewalld/services/apy.xml
firewall-cmd --permanent --add-service=apy
firewall-cmd --permanent --add-service=https
firewall-cmd --reload

# TODO: Will this require more options the first time around?
certbot --agree-tos -m unhammer+apertium@mm.st --apache -n certonly -d gtweb.uit.no

systemctl daemon-reload
systemctl enable apy.service restart-apy.timer dnf-automatic.timer certbot.timer
systemctl start  apy.service restart-apy.timer dnf-automatic.timer certbot.timer
