* Introduction

This repository contains the configuration for the MT interfaces at
- http://gtweb.uit.no/jorgal/
- http://gtweb.uit.no/tolkimine/
- http://gtweb.uit.no/mt-testing/

The translation daemon/server is running under the user "apy" on the
server gtweb (gtweb.uit.no), and the html pages also reside under the
home directory of that user (hosted by the regular Apache server). The
whole configuration is in this git repo, hosted at
[[https://github.com/unhammer/gtweb-apy-conf#readme][https://github.com/unhammer/gtweb-apy-conf]]

The directory =/home/apy= is a git repo, with
https://github.com/unhammer/gtweb-apy-conf as the upstream.

Any change to the configuration is first checked in to git and pushed
to github, then the configuration is updated at gtweb by running the
=update= script, which also might update submodules and build them.

There are two submodules:
- the translation daemon/server [[https://github.com/goavki/apertium-apy/tree/giellatekno/][apertium-apy]], branch giellatekno
- the static html pages [[https://github.com/goavki/apertium-html-tools/tree/giellatekno/][apertium-html-tools]], branch giellatekno

The following sections define how to do common or uncommon tasks like
installing everything from scratch, installing new language pairs,
or updating the code for the subrepos.


* Installing new language pairs

** Optionally enable it in jorgal/tolkimine

The page [[http://gtweb.uit.no/mt-testing/][mt-testing]] runs all language pairs, but [[http://gtweb.uit.no/jorgal/][jorgal]] and [[http://gtweb.uit.no/tolkimine/][tolkimine]]
only run certain pairs. See the files [[file:html-tools-confs/jorgal.conf::ALLOWED_PAIRS%20%3D%20sme-nob,%20sme-fin][jorgal.conf]] / [[file:html-tools-confs/jorgal.conf::ALLOWED_PAIRS%20%3D%20sme-nob,%20sme-fin][tolkimine.conf]] in
the directory =html-tools-confs= – you'll need to edit the line
=ALLOWED_PAIRS= if you want your new pair to appear on one of those
pages. Then check in your change and push to
[[https://github.com/unhammer/gtweb-apy-conf]] (it's also possible to just
check in that change on =/home/apy= without pushing, if you really
have to), e.g.

: edit html-tools-confs/jorgal.conf
: git commit -am "added sme-eus"
: git push # unless you're editing in /home/apy because you can't push

** Install the pair and re-build pages

To install the new language pair on gtweb, log in as a user with
sudo-rights and do:

: sudo dnf install apertium-from-to
: sudo /home/apy/update


* Updating submodules apertium-apy / apertium-html-tools

A push to apertium-apy or apertium-html-tools isn't automatically
pulled into the gtweb just by running =/home/apy/update=; you need to
also check into this repo that you want to use that.

This repo specifies which commit of each submodule we want to use. If
you want to use the newest commit of the =giellatekno= branch of
apertium-html-tools and apertium-apy, you can enter this repo and do

: git submodule foreach git pull origin giellatekno
: git commit -m "updated apy/html-tools"
: git push

(if you don't have push-rights to
https://github.com/unhammer/gtweb-apy-conf, you could just run the
first two lines under =gtweb:/home/apy=).

Then, as a sudo-user on gtweb, do:

: sudo /home/apy/update



* In case everything needs reinstalling

In case e.g. gtweb dies and you need to reinstall everything:

Install certbot for https:
: sudo dnf install python3-certbot-apache

Install language pairs from Tino's repo:

: curl -Ss https://apertium.projectjj.com/rpm/install-nightly.sh | sudo bash
: sudo dnf install giella-sme       # for divvun-gramcheck
: sudo dnf install apertium-sme-nob # and other language pairs for MT

and dependencies of divvun-gramcheck:

: sudo dnf install hfst-ospell-devel libarchive-devel

- add a new user =apy= (group =apy=) with home dir =/home/apy=
- log in as this user =apy=, and run

: cd /home/apy
: git init
: git remote add origin https://github.com/unhammer/gtweb-apy-conf.git
: git branch --set-upstream-to=origin/master master
: git pull
: git submodule init
: git submodule update --recursive
: svn co https://gtsvn.uit.no/langtech/trunk GTHOME
: # Use the compiled generator that comes with the dnf package giella-sme:
: ln -s /usr/share/giella/sme/generator-gt-norm.hfstol GTHOME/langs/sme/tools/grammarcheckers/

Unfortunately giella-sme doesn't yet include the blanktagger and
grammar checker-specific spelling lexicon (and gtweb doesn't have
enough memory to compile giella-sme), so from a different machine do:
: scp $GTHOME/langs/sme/tools/grammarcheckers/analyser-gt-whitespace.hfst        apy@gtweb:GTHOME/langs/sme/tools/grammarcheckers/
: scp $GTHOME/langs/sme/tools/grammarcheckers/acceptor.default.hfst              apy@gtweb:GTHOME/langs/sme/tools/grammarcheckers/
: scp $GTHOME/langs/sme/tools/grammarcheckers/errmodel.default.hfst              apy@gtweb:GTHOME/langs/sme/tools/grammarcheckers/
(Note: At some point in the future, the grammarchecker generator will
also differ from what's installed by giella-sme, in which case we'll
either have to scp it or include it in a package somehow.)

Then log in as a user with sudo-rights, and install configuration files:
: sudo /home/apy/install-and-enable-services

That script will also ensure that the dnf updater, apertium-apy
service and apertium-apy-restarter service are running now and on
restarts of gtweb.

Then update and build apertium-apy and the apertium-html-tools pages:
: sudo /home/apy/update

** PDF translation support
This uses CorpusTools if available. We need to ensure it's possible to
run =/usr/bin/pdftohtml= and to do =from corpustools import
pdfconverter= from the apy directory, and currently this is done with:

: sudo dnf install poppler-utils
: svn co --depth immediates https://victorio.uit.no/langtech/trunk/tools/CorpusTools/corpustools /home/apy/apertium-apy/corpustools
: svn up --set-depth infinity /home/apy/apertium-apy/corpustools/{xslt,xml,dtd}

APY will detect if corpustools and pdftohtml are available.

** Details

All the relevant configuration files for the gtweb machine are under
the =etc= folder of this repo, so we know what configs are relevant in
case we need to reinstall everything.

Language pairs are those that are installed with =dnf install=
(=ExecStart= in =etc/systemd/system/apy.service= gives the path to the
modes files), but individual html configurations can specify a subset
of pairs to run (see [[https://github.com/unhammer/gtweb-apy-conf#installing-new-language-pairs][Installing new language pairs]]).

We expect a standard Apache httpd running; see configs in
=etc/httpd/conf.d/=.

The file =etc/systemd/system/apy.service= says how to run the
apertium-apy MT daemon, which is started on restart of the gtweb
machine.

