#!/bin/bash

set -e -u

git submodule foreach git pull origin giellatekno 

git commit -am "updated submodules" 

git push || echo 'Failed pushing!'

echo "From gtweb, do 'sudo /home/apy/update' to update the configuration and re-build"
