#!/bin/bash

set -e -u

# git submodule foreach git pull origin giellatekno
for submodule in apertium-apy/ apertium-html-tools/; do
    ( cd "${submodule}" && git pull origin giellatekno )
done
for submodule in divvun-gramcheck/ divvun-webdemo/ ckeditor-divvungc/; do
    ( cd "${submodule}" && git pull origin master )
done

git commit apertium-apy/ apertium-html-tools/ divvun-gramcheck/ divvun-webdemo/ ckeditor-divvungc/ -m "updated submodules"

git push || echo 'Failed pushing!'

echo
echo "From gtweb, do 'sudo /home/apy/update' to update the configuration and re-build"
