#!/bin/bash

set -e -u

if [[ "$(whoami)" != root ]]; then
    echo "Run this script with sudo" >&2
    exit 1
fi

D="$(dirname "$0")"
declare -r D

# In case the "git pull" updates this script itself, we put it all in
# a function, since bash reads the file as it's executing it:
# http://stackoverflow.com/a/18036284/69663
main () {
    cd "$D"
    if find . -not -uid "$(id -u apy)" | grep .; then
        echo "Found files not owned by apy here, please chown apy:apy" >&2
        exit 1
    elif grep -q @GLIB_CFLAGS@ /usr/lib64/pkgconfig/hfst.pc; then
        echo "Please run \"sed -i.orig 's/@GLIB_CFLAGS@//' /usr/lib64/pkgconfig/hfst.pc\"" >&2
        exit 1
    fi

    sudo -u apy git pull
    sudo -u apy git submodule update --init --recursive

    sudo -u apy ./build-apy-server
    rsync -avh --delete /home/apy/apertium-html-tools/ /opt/apy/

    systemctl restart apy
    sleep 1
    sudo -u apy ./build-html-pages

    mkdir -p /opt/gc/html/ck
    ( cd ./divvun-webdemo/    && cp -r -- lib index.html ./*.css locales            /opt/gc/html/    )
    ( cd ./ckeditor-divvungc/ && cp -r -- lib index.html ./*.css locales ck-plugins /opt/gc/html/ck/ )

    if ! find etc/ usr/ -type f -print0 | xargs -r0I{} diff -q '{}' '/{}'; then
        echo "Configuration files changed – you should run $D/install-and-enable-services"
    else
        systemctl status apy
    fi
}

main
